### ISSUE TITLE
Copy_data_path freezes upon first trial

### ISSUE THREAD

**Issue by CyrilRJK** [DIAGNijmegen/pathology-whole-slide-data#2]
When copying data to docker container from a config file using: 

dataset: 
    copy_path: /home/user/data
    

Initialising the batch_iterator freezes on the first attempt. Waiting for the copying to finish, stopping the running code block and re-running it produces the expected results. The output on the first attempt is below, output on second attempt below that:

Config files + code listed at the bottom of the post.

First attempt:
---------------------------------------------------------------------

`Copied from '/data/pathology/projects/pathology-multires-segmentation/data/breastdataset/images/data_lvl1/999.tif'
Copied to: '/home/user/data/T999.tif'
...
Destination path '/home/user/data/T999.tif' already exists

Process ProducerForkProcess-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/.local/lib/python3.8/site-packages/concurrentbuffer/producer.py", line 58, in run
    self._producer.build()
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/buffer/batchproducer.py", line 20, in build
    build = self._config_builder.build_instances()
  File "/home/user/.local/lib/python3.8/site-packages/creationism/configuration/config.py", line 320, in build_instances
    build[mode][key] = build[mode][key].build(configurations)
  File "/home/user/.local/lib/python3.8/site-packages/creationism/configuration/config.py", line 242, in build
    return ConfigObject(_build_object(self, module, attribute))
  File "/home/user/.local/lib/python3.8/site-packages/creationism/configuration/config.py", line 350, in _build_object
    return attribute(**builds.cast())
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 131, in __init__
    super().__init__(mode, associations, labels, renamed_labels)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 40, in __init__
    self.data = self._open(self._associations)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 143, in _open
    ] = self._open_image(wsi_file)

Destination path '/home/user/data/T999.tif' already exists

  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 156, in _open_image
    return wsi_file.open()

  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/source/files.py", line 86, in open
    return WholeSlideImage(self.path, self._image_backend)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/image/wholeslideimage.py", line 19, in __init__
    self._backend = WholeSlideImageBackend.create(backend, path=self._path)
Process ProducerForkProcess-5:
  File "/home/user/.local/lib/python3.8/site-packages/creationism/registration/factory.py", line 89, in create
    return cls._create(class_type, *args, **kwargs)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/creationism/registration/factory.py", line 98, in _create
    return class_type(*args, **kwargs)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/user/.local/lib/python3.8/site-packages/concurrentbuffer/producer.py", line 58, in run
    self._producer.build()
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/image/backend.py", line 150, in __init__
    OpenSlide.__init__(self, str(path))
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/buffer/batchproducer.py", line 20, in build
    build = self._config_builder.build_instances()
  File "/home/user/.local/lib/python3.8/site-packages/openslide/__init__.py", line 160, in __init__
    self._osr = lowlevel.open(filename)
  File "/home/user/.local/lib/python3.8/site-packages/creationism/configuration/config.py", line 320, in build_instances
    build[mode][key] = build[mode][key].build(configurations)
  File "/home/user/.local/lib/python3.8/site-packages/openslide/lowlevel.py", line 128, in _check_open
    raise OpenSlideUnsupportedFormatError(
  File "/home/user/.local/lib/python3.8/site-packages/creationism/configuration/config.py", line 242, in build
    return ConfigObject(_build_object(self, module, attribute))
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file
  File "/home/user/.local/lib/python3.8/site-packages/creationism/configuration/config.py", line 350, in _build_object
    return attribute(**builds.cast())
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 131, in __init__
    super().__init__(mode, associations, labels, renamed_labels)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 40, in __init__
    self.data = self._open(self._associations)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 143, in _open
    ] = self._open_image(wsi_file)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/dataset.py", line 156, in _open_image
    return wsi_file.open()
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/source/files.py", line 86, in open
    return WholeSlideImage(self.path, self._image_backend)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/image/wholeslideimage.py", line 19, in __init__
    self._backend = WholeSlideImageBackend.create(backend, path=self._path)
  File "/home/user/.local/lib/python3.8/site-packages/creationism/registration/factory.py", line 89, in create
    return cls._create(class_type, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/creationism/registration/factory.py", line 98, in _create
    return class_type(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/wholeslidedata/image/backend.py", line 150, in __init__
    OpenSlide.__init__(self, str(path))
  File "/home/user/.local/lib/python3.8/site-packages/openslide/__init__.py", line 160, in __init__
    self._osr = lowlevel.open(filename)
  File "/home/user/.local/lib/python3.8/site-packages/openslide/lowlevel.py", line 128, in _check_open
    raise OpenSlideUnsupportedFormatError(
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

Copied from '/data/pathology/projects/pathology-proacting/bcts/rumc_dcis_annotations/annotations_lv1_corrected_necrosis_witali_xml/T999.xml'
Copied to: '/home/user/data/T999.xml'
...`

Second attempt:
---------------------------------------------------------------------
Destination path '/home/user/data/T999.tif' already exists
Destination path '/home/user/data/T999.xml' already exists
Destination path '/home/user/data/T999.tif' already existsDestination path '/home/user/data/T999.tif' already exists

Destination path '/home/user/data/T998.tif' already exists
Destination path '/home/user/data/T999.xml' already existsDestination path '/home/user/data/T999.xml' already exists

Destination path '/home/user/data/T998.xml' already exists
Destination path '/home/user/data/T998.tif' already existsDestination path '/home/user/data/T998.tif' already exists

Destination path '/home/user/data/T998.xml' already existsDestination path '/home/user/data/T998.xml' already exists

Code to reproduce:
---------------------------------------------------------------------
from wholeslidedata.iterators import create_batch_iterator
from plot_utils import init_plot, plot_batch, show_plot

user_config = './
config.yml'
batches = 2 # how many batches that are going to be sampled, batchgenerator will be reset afterwards
repeats = 1 
cpus = 2
mode = 'training'

training_batch_generator = create_batch_iterator(user_config=user_config, 
                            batches=batches, 
                            mode=mode, 
                            cpus=cpus)

for r in range(repeats):
    fig, axes = init_plot(batches, training_batch_generator.batch_size)
    for idx, (x_batch, y_batch) in enumerate(training_batch_generator):
        plot_batch(axes, idx, x_batch, y_batch)
    show_plot(fig, r)

**Comment by martvanrijthoven** [comment]
Fixed in version 0.0.7
